"""Regenerate ``sources/embed/vocabulary.py`` from the EMBED clinical-semantic catalog.

Requires the ``embed-context`` command from the embed-mcp project and a
catalog-set manifest. Only catalog metadata (code meanings) is read; no EMBED
data is accessed.

    python -m tools.generate_embed_vocabulary \\
        --catalog ~/AgentFiles/projects/embed-mcp/catalog/internal-v2-catalog-set.json
"""

from __future__ import annotations

import argparse
import datetime
import json
import pprint
import subprocess
from pathlib import Path
from typing import Dict, List, Tuple

TARGET = Path(__file__).resolve().parents[1] / "src" / "embed_data_model" / "sources" / "embed" / "vocabulary.py"

# (constant name, catalog feature, description)
FEATURES: List[Tuple[str, str, str]] = [
    ("ASSESSMENT", "imaging.assessment", "BI-RADS assessment (asses)"),
    ("RECOMMENDATION", "imaging.recommendation", "Imaging recommendation (recc); comma-separated, unordered"),
    ("DENSITY", "exam.tissue_density", "Breast tissue density (tissueden); not an ordinal scale"),
    ("EXAM_TYPE", "exam.mammography_type", "Mammography exam type (mg_exam_type)"),
    ("VISIT_TYPE", "exam.visit_type", "Visit type (vtype)"),
    ("EXAM_MODALITY", "exam.modality", "Exam modality (modality_desc)"),
    ("MASS_SHAPE", "mammography.mass_shape", "Mass shape (massshape); also carries asymmetry, distortion and lymph-node codes"),
    ("MASS_MARGIN", "mammography.mass_margin", "Mass margin (massmargin)"),
    ("MASS_DENSITY", "mammography.mass_density", "Mass density (massdens)"),
    (
        "CALCIFICATION_MORPHOLOGY",
        "mammography.calcification_morphology",
        "Calcification morphology (calcfind); comma-separated, unordered",
    ),
    ("CALCIFICATION_DISTRIBUTION", "mammography.calcification_distribution", "Calcification distribution (calcdistri)"),
    ("OTHER_FINDING", "mammography.other_finding", "Other finding (otherfind); comma-separated, unordered"),
    ("IMPLANT_FINDING", "mammography.implant_finding", "Implant finding (implanfind); comma-separated, unordered"),
    ("PROCEDURE_TYPE", "pathology.biopsy_type", "Procedure type (type)"),
    ("PATHOLOGY_DESCRIPTOR", "pathology.diagnosis_code_slot", "Pathology descriptor slots (path1-path10)"),
    ("EXPOSURE_CATEGORY", "internal-v2.hormone_history.exposure_category", "Hormone-history exposure category (type)"),
    ("HORMONE", "internal-v2.hormone_history.hormone_code", "Hormone-history code when the category is H (code)"),
    ("THERAPY", "internal-v2.hormone_history.therapy_code", "Hormone-history code when the category is T (code)"),
    ("CONTRACEPTIVE", "internal-v2.hormone_history.contraceptive_code", "Hormone-history code when the category is O (code)"),
    ("PROCEDURE_HISTORY_CATEGORY", "internal-v2.procedure_history.procedure_category", "Procedure-history category (type)"),
    ("BREAST_PROCEDURE", "internal-v2.procedure_history.breast_procedure_code", "Procedure-history code when the category is B (pcode)"),
    (
        "GYNECOLOGICAL_PROCEDURE",
        "internal-v2.procedure_history.gynecological_procedure_code",
        "Procedure-history code when the category is G (pcode)",
    ),
    (
        "PROCEDURE_HISTORY_RESULT",
        "internal-v2.procedure_history.reported_result",
        "Reported prior-procedure result (result); combined tokens such as FA,SF are not split",
    ),
]

HEADER = '''"""Meanings of EMBED MagView codes, for decoding source codes into ``Code`` values.

Generated by ``tools/generate_embed_vocabulary.py`` from the EMBED
clinical-semantic catalog (profile ``{profile}``) on {day}. Meanings are copied
verbatim from the catalog's release-legend vocabularies. Codes the catalog marks
as unresolved, and codes absent from its lists, decode with no meaning; their
source code is kept. Lists are not guaranteed exhaustive.

Regenerate from the catalog rather than editing a table by hand.
"""

from __future__ import annotations

from embed_data_model.core.codes import Vocabulary

PRESENCE = Vocabulary("presence", {{"0": "Not represented", "1": "Represented"}})
"""Presence flags (mass, asymmetry, arch_distortion, calc): 0 or 1."""

CALCIFICATION_NUMBER = Vocabulary("calcification_number", {{}})
"""Number of calcifications (calcnumber): a count kept as its source text; no meanings."""
'''


def vocabulary(catalog: str, profile: str, feature: str) -> Tuple[Dict[str, str], bool]:
    """Return the resolved meanings of a feature and whether its codes are comma-separated."""

    output = subprocess.run(
        ["embed-context", "--catalog", catalog, "--format", "json", "feature", "--include-codes", "--profile", profile, feature],
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    data = json.loads(output)["data"]["vocabulary"]
    table: Dict[str, str] = {}
    for code, meaning in data["codes"].items():
        key = code.strip().upper()
        if "unresolved" in meaning.lower() or key in table:
            continue
        table[key] = meaning.strip()
    return table, data.get("parsing") == "comma_delimited_unordered"


def render(catalog: str, profile: str) -> str:
    parts = [HEADER.format(profile=profile, day=datetime.date.today().isoformat())]
    for name, feature, description in FEATURES:
        table, delimited = vocabulary(catalog, profile, feature)
        body = pprint.pformat(table, width=88, sort_dicts=True).replace("\n", "\n    ")
        flag = "    delimited=True,\n" if delimited else ""
        parts.append(f'\n{name} = Vocabulary(\n    "{name.lower()}",\n    {body},\n{flag})\n"""{description}."""\n')
    return "".join(parts)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--catalog", required=True, help="catalog-set manifest for embed-context")
    parser.add_argument("--profile", default="internal-v2")
    args = parser.parse_args()
    TARGET.write_text(render(str(Path(args.catalog).expanduser()), args.profile))
    print(f"wrote {TARGET}")


if __name__ == "__main__":
    main()
